# Generated by Django 3.2.5 on 2021-08-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stock',
        ),
    ]
