# Generated by Django 3.2.5 on 2021-08-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Tag Name')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Registered Time')),
            ],
            options={
                'verbose_name': 'BOARD TAG',
                'verbose_name_plural': 'BOARD TAG',
                'db_table': 'community_tag',
            },
        ),
    ]
