# Generated by Django 3.2.5 on 2021-08-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='PRODUCT NAME')),
                ('price', models.IntegerField(verbose_name='PRODUCT PRICE')),
                ('description', models.TextField(verbose_name='PRODUCT DESCRIPTION')),
                ('stock', models.IntegerField(verbose_name='STOCK')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='REGI DATE')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
                'db_table': 'Shopping_Product',
            },
        ),
    ]
