# Generated by Django 3.2.5 on 2021-08-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fcuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='User Name')),
                ('useremail', models.EmailField(max_length=128, verbose_name='User Email')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Registered Time')),
            ],
            options={
                'verbose_name': 'Fcuser 사용자',
                'verbose_name_plural': 'Fcuser 사용자',
                'db_table': 'community_fcuser',
            },
        ),
    ]
