# Generated by Django 3.2.5 on 2021-07-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': 'Fcuser 사용자', 'verbose_name_plural': 'Fcuser 사용자'},
        ),
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default='none@gmail.com', max_length=128, verbose_name='User Email'),
            preserve_default=False,
        ),
    ]
